export const APP_NAV_ITEMS = [
  { href: '/dashboard', label: 'Dashboard' },
  { href: '/onboarding', label: 'Onboarding' },
  { href: '/assets', label: 'Assets' },
  { href: '/targets', label: 'Targets' },
  { href: '/threat', label: 'Threat Monitoring' },
  { href: '/compliance', label: 'Compliance Controls' },
  { href: '/resilience', label: 'Resilience Monitoring' },
  { href: '/alerts', label: 'Alerts' },
  { href: '/exports', label: 'Exports' },
  { href: '/integrations', label: 'Integrations' },
  { href: '/templates', label: 'Templates' },
  { href: '/settings', label: 'Settings' },
  { href: '/help', label: 'Help' },
] as const;
